/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4gQ42McBSuc
 */

import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

import { login } from "@/lib/actionLogin";
import { useFormState } from "react-dom";

export function LoginPage() {
  const initState = {
    message: "",
  };

  const [state, formAction] = useFormState(login, initState);
  return (
    <>
      <div className="overflow-hidden">
        <div className="flex flex-col items-center justify-center p-4 min-h-screen bg-gray-100 dark:bg-gray-800">
          <div className="mx-auto max-w-sm space-y-6">
            <div className="space-y-2 text-center">
              <h1 className="text-3xl font-bold">Probsolve-Score</h1>
              <p className="text-gray-500 dark:text-gray-400">
                คะแนนเก็บ Probsolve 60% + 10% (optional) ตอนนี้คุณมีเท่าไร?
                เราจะช่วยนับคะแนนให้เอง
              </p>
            </div>
            <div className="space-y-4">
              <form action={formAction}>
                <div className="space-y-2">
                  <Label htmlFor="username">Nontri Account</Label>
                  <Input name="username" placeholder="b651050xxxx" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="password">Password</Label>
                  <Input
                    name="password"
                    placeholder="f44h8"
                    required
                    type="password"
                  />
                </div>
                <div className="pt-4">
                  <Button className="w-full" type="submit">
                    Login
                  </Button>
                </div>
              </form>
              <Link
                className="inline-block w-full text-center text-sm underline"
                href="https://www.instagram.com/faithpanupong"
              >
                เจอบัคหรอ? แจ้งมาเลย 🥹
              </Link>
            </div>
          </div>
        </div>

        <footer className="fixed bottom-0 w-full p-4  text-center bg-gray-200 dark:bg-gray-700">
          <p className="text-gray-600 dark:text-gray-300">
            {`ไม่ phishing คับดูโค้ดได้ที่ `}
            <Link className="text-blue-500 underline" href="#">
              GitHub
            </Link>
          </p>
          <p className="text-xs text-gray-500 dark:text-gray-400">
            {`"เพราะเราก็ขี้เกียจนับคะแนนเองเหมือนกัน😔"`}
          </p>
        </footer>
      </div>
    </>
  );
}
