// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/4gQ42McBSuc
//  */
// import { Label } from "@/components/ui/label";
// import { Input } from "@/components/ui/input";
// import { Button } from "@/components/ui/button";
// import { Footer } from "@/components/component/footer";
// import Link from "next/link";

// import { login } from "@/lib/actionLogin";
// import { useFormState } from "react-dom";
// import Chart from "./donut-2";
// import Image from "next/image";

// export function LoginPage() {
//   const initState = {
//     message: "",
//     myName: "",
//     maxNormalPercent: 0,
//     maxOptionalPercent: 0,
//     myNormalPercent: 0,
//     myOptionalPercent: 0,
//     realOptionalPercent: 0,
//     leftOverPercent: 0,
//   };

//   const [state, formAction] = useFormState(login, initState);

//   const chartData = [
//     { name: "A", value: state.myNormalPercent, color: "#0B60B0" },
//     { name: "B", value: state.realOptionalPercent, color: "#40A2D8" },
//     {
//       name: "C",
//       value: state.leftOverPercent,
//       color: "#F0EDCF",
//     },
//   ];

//   return (
//     <>
//       {state.message == "" ? (
//         <div className="overflow-hidden">
//           <div className="flex flex-col items-center justify-center p-4 min-h-screen bg-gray-100 dark:bg-gray-800">
//             <div className="mx-auto max-w-sm space-y-6">
//               <div className="space-y-2 text-center">
//                 <h1 className="text-3xl font-bold">Probsolve-Score</h1>
//                 <p className="text-gray-500 dark:text-gray-400">
//                   คะแนนเก็บ Probsolve 60% + 10% (optional) ตอนนี้คุณมีเท่าไร?
//                   เราจะช่วยนับคะแนนให้เอง
//                 </p>
//               </div>
//               <div className="space-y-4">
//                 <form action={formAction}>
//                   <div className="space-y-2">
//                     <Label htmlFor="username">Nontri Account</Label>
//                     <Input name="username" placeholder="b651050xxxx" required />
//                   </div>
//                   <div className="space-y-2">
//                     <Label htmlFor="password">Password</Label>
//                     <Input
//                       name="password"
//                       placeholder="f44h8"
//                       required
//                       type="password"
//                     />
//                   </div>
//                   <div className="pt-4">
//                     <Button className="w-full" type="submit">
//                       Login
//                     </Button>
//                   </div>
//                 </form>
//                 <Link
//                   className="inline-block w-full text-center text-sm underline"
//                   href="https://www.instagram.com/faithpanupong"
//                 >
//                   เจอบัคหรอ? แจ้งมาเลย 🥹
//                 </Link>
//               </div>
//             </div>
//           </div>

//           <Footer />
//         </div>
//       ) : (
//         <div>
//           <div className="flex flex-col min-h-screen  bg-gray-100 ">
//             <header className="flex items-center justify-between px-6 py-4 bg-gray-200 dark:bg-[#333]">
//               <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
//                 My Problem Solve
//               </h1>
//               <Link href={"/"}>
//                 <Button
//                   className="text-gray-900 dark:text-gray-100"
//                   variant="outline"
//                 >
//                   Logout
//                 </Button>
//               </Link>
//             </header>

//             <div className="flex flex-col items-center justify-center p-10">
//               <div className="mx-auto max-w-sm space-y-6">
//                 <div className="space-y-2 text-center">
//                   <h1 className="pt-8 text-3xl font-bold">Your Score</h1>
//                   <p className="text-gray-500 dark:text-gray-400">
//                     ID: 6510503671
//                   </p>
//                   <div className="p-4">
//                     <Chart data={chartData} />
//                   </div>
//                   <div className="pt-4 text-xl font-bold">
//                     Homework Score:{" "}
//                     <p className="font-normal">
//                       {state.myNormalPercent}/{state.maxNormalPercent}
//                     </p>
//                   </div>
//                   {state.myOptionalPercent >= state.maxOptionalPercent ? (
//                     <div>
//                       <div className="font-extrabold text-transparent text-xl bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
//                         Optional Score:{" "}
//                         <p className="font-normal">
//                           {state.myOptionalPercent}/{state.maxOptionalPercent}
//                         </p>
//                       </div>
//                       เก่งมาก {state.myName} 😲👍 คะแนนของคุณเกินมา {1}{" "}
//                       ปลดล็อกสกินจิตรทัศน์สีรุ้ง!
//                     </div>
//                   ) : (
//                     <div className="pt-4 text-xl font-bold">
//                       Optional Score:{" "}
//                       <p className="font-normal">
//                         {state.myOptionalPercent}/{state.maxOptionalPercent}
//                       </p>
//                     </div>
//                   )}
//                 </div>
//               </div>
//             </div>

//             <Footer />
//           </div>
//         </div>
//       )}
//     </>
//   );
// }
